<?php
/**
 * Copyright © 2017 PT Kemana Teknologi Solusi. All rights reserved.
 * http://www.kemana.com
 */
/**
 * @category Training3
 * @package  Training3_OrderInfo
 * @license  http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author   Kemana Team
 *
 */

$orderData = $block->getOrderData();
?>

<?php if ($orderData) :?>
<table border="1" cellpadding="5" cellspacing="0">
    <?php foreach ($orderData as $key => $value) :?>
        <tr>
            <td><?php echo $key ?></td>
            <td>:</td>
            <td>
                <?php if (is_array($value)) :?>
                <?php $i = 1;?>
                    <?php foreach ($value as $keyValue => $itemValue) :?>
                        <?php echo __('Item %1 %2 <br/>', $i, var_export($itemValue, true));?>
                        <?php $i++;?>
                    <?php endforeach;?>
                <?php else :?>
                    <?php echo $value ?>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach;?>
</table>
<?php else :?>
    <h3><?php echo __('Order not found');?></h3>
<?php endif;?>
