<?php
/**
 * Copyright © 2017 PT Kemana Teknologi Solusi. All rights reserved.
 * http://www.kemana.com
 */

/**
 * @category Training5
 * @package  Training5_VendorRepository
 * @license  http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 *
 *
 * @author   Kemana Team
 *
 */
 
$vendors = $block->getAllVendor();

echo __('Vendor List <br>');
foreach ($vendors[0] as $vendor_id => $vendor_name) :
    echo __('Vendor Id : %1 | Vendor Name : %2 <br>', $vendor_id, $vendor_name);
endforeach;
echo '<br><br>';


echo __('Vendor Name : %1 <br>', $vendors[1]);
echo '<br><br>';


echo __('Products ID List : <br>');
$product_ids = '';
foreach ($vendors[2] as $product_id) :
    $product_ids .= $product_id . ', ';
endforeach;
echo $product_ids . '<br>';
echo '<br><br>';


echo __('Sort Vendor by Name : <br>');
foreach ($vendors[3] as $vendor_name) :
    echo $vendor_name . '<br>';
endforeach;
echo '<br><br>';


echo __('Filter Vendor by Name (Google): <br>');
foreach ($vendors[4] as $vendor_name) :
    echo $vendor_name . '<br>';
endforeach;
echo '<br><br>';

echo __("Test 'OR' Filter Vendor by Name (Google & Apple): <br>");
foreach ($vendors[5] as $vendor_name) :
    echo $vendor_name . '<br>';
endforeach;
echo '<br><br>';
